server:
  port: 8090

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
      - id: enquiry-service
        uri: lb://ENQUIRY-SERVICE
        predicates:
        - Path=/enquiries/**
        filters:
        - name: RequestSize
          args:
            maxSize: 5000000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
